set nu ai si cindent et ts=4 sw=4 so=10 nosm nohls
inoremap {} {}<left><return><up><end><return> " remap pra chaves
au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal! g'\"" | endif " volta pro lugar onde estava quando saiu do arquivo
