name: clang-format Checker

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
  push:
    branches:
      - test/**  # Permite testar em branches test/nome-do-teste
      
  # A verificação no 'push' pra 'main' foi desabilitada por ser redundante.
  # Já que push direto na main está bloqueado e tudo tem que passar por um PR que já vai rodar essa action.
  # push:
  #   branches:
  #     - main
      
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build container image
        run: |
          docker build -t almanaque-builder -f docker/Dockerfile .

      - name: Run clang-format style check for C++ programs
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            almanaque-builder \
            find Codigos -name "*.cpp" -exec clang-format --dry-run --Werror {} \;
