name: Gerar Almanaque PDF

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - test/**  # Permite testar em branches test/nome-do-teste

jobs:
  build_and_commit_pdf:
    if: "!contains(github.event.head_commit.message, 'chore: Atualiza o PDF')"

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build container image
        run: |
          docker build -t almanaque-builder -f docker/Dockerfile .

      - name: Run PDF generation script using container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            almanaque-builder \
            python3 .github/scripts/pdfer.py

      - name: Create Pull Request com o novo PDF
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: Atualiza o PDF"

          title: "chore: Atualiza o PDF"
          body: |
            Este PR foi aberto automaticamente pelo GitHub Actions. 🤖

            O PDF do Almanaque foi atualizado para refletir as últimas mudanças nos códigos-fonte e/ou arquivos LaTeX.
          branch: "chore/gerar-pdf-${{ github.run_number }}"
          base: main
          delete-branch: true
          sign-commits: true
